// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: protostuff/kv_store.proto

package kvpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Key struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyVal        int32                  `protobuf:"varint,1,opt,name=key_val,json=keyVal,proto3" json:"key_val,omitempty"`
	FromClient    bool                   `protobuf:"varint,2,opt,name=from_client,json=fromClient,proto3" json:"from_client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Key) Reset() {
	*x = Key{}
	mi := &file_protostuff_kv_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_protostuff_kv_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_protostuff_kv_store_proto_rawDescGZIP(), []int{0}
}

func (x *Key) GetKeyVal() int32 {
	if x != nil {
		return x.KeyVal
	}
	return 0
}

func (x *Key) GetFromClient() bool {
	if x != nil {
		return x.FromClient
	}
	return false
}

type Value struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_protostuff_kv_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_protostuff_kv_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_protostuff_kv_store_proto_rawDescGZIP(), []int{1}
}

func (x *Value) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyVal        int32                  `protobuf:"varint,1,opt,name=key_val,json=keyVal,proto3" json:"key_val,omitempty"`
	Val           string                 `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	FromClient    bool                   `protobuf:"varint,3,opt,name=from_client,json=fromClient,proto3" json:"from_client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_protostuff_kv_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protostuff_kv_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_protostuff_kv_store_proto_rawDescGZIP(), []int{2}
}

func (x *SetRequest) GetKeyVal() int32 {
	if x != nil {
		return x.KeyVal
	}
	return 0
}

func (x *SetRequest) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

func (x *SetRequest) GetFromClient() bool {
	if x != nil {
		return x.FromClient
	}
	return false
}

type DeleteInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Existed       bool                   `protobuf:"varint,1,opt,name=existed,proto3" json:"existed,omitempty"`
	Val           string                 `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInfo) Reset() {
	*x = DeleteInfo{}
	mi := &file_protostuff_kv_store_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInfo) ProtoMessage() {}

func (x *DeleteInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protostuff_kv_store_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInfo.ProtoReflect.Descriptor instead.
func (*DeleteInfo) Descriptor() ([]byte, []int) {
	return file_protostuff_kv_store_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteInfo) GetExisted() bool {
	if x != nil {
		return x.Existed
	}
	return false
}

func (x *DeleteInfo) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

var File_protostuff_kv_store_proto protoreflect.FileDescriptor

const file_protostuff_kv_store_proto_rawDesc = "" +
	"\n" +
	"\x19protostuff/kv_store.proto\x12\x02kv\"?\n" +
	"\x03Key\x12\x17\n" +
	"\akey_val\x18\x01 \x01(\x05R\x06keyVal\x12\x1f\n" +
	"\vfrom_client\x18\x02 \x01(\bR\n" +
	"fromClient\"\x19\n" +
	"\x05Value\x12\x10\n" +
	"\x03val\x18\x01 \x01(\tR\x03val\"X\n" +
	"\n" +
	"SetRequest\x12\x17\n" +
	"\akey_val\x18\x01 \x01(\x05R\x06keyVal\x12\x10\n" +
	"\x03val\x18\x02 \x01(\tR\x03val\x12\x1f\n" +
	"\vfrom_client\x18\x03 \x01(\bR\n" +
	"fromClient\"8\n" +
	"\n" +
	"DeleteInfo\x12\x18\n" +
	"\aexisted\x18\x01 \x01(\bR\aexisted\x12\x10\n" +
	"\x03val\x18\x02 \x01(\tR\x03val2\x90\x01\n" +
	"\aKVStore\x12\x1b\n" +
	"\x03Get\x12\a.kv.Key\x1a\t.kv.Value\"\x00\x12\"\n" +
	"\x03Set\x12\x0e.kv.SetRequest\x1a\t.kv.Value\"\x00\x12#\n" +
	"\x06Delete\x12\a.kv.Key\x1a\x0e.kv.DeleteInfo\"\x00\x12\x1f\n" +
	"\x05Watch\x12\a.kv.Key\x1a\t.kv.Value\"\x000\x01B\x19Z\x17gocurrencylearning/kvpbb\x06proto3"

var (
	file_protostuff_kv_store_proto_rawDescOnce sync.Once
	file_protostuff_kv_store_proto_rawDescData []byte
)

func file_protostuff_kv_store_proto_rawDescGZIP() []byte {
	file_protostuff_kv_store_proto_rawDescOnce.Do(func() {
		file_protostuff_kv_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protostuff_kv_store_proto_rawDesc), len(file_protostuff_kv_store_proto_rawDesc)))
	})
	return file_protostuff_kv_store_proto_rawDescData
}

var file_protostuff_kv_store_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protostuff_kv_store_proto_goTypes = []any{
	(*Key)(nil),        // 0: kv.Key
	(*Value)(nil),      // 1: kv.Value
	(*SetRequest)(nil), // 2: kv.SetRequest
	(*DeleteInfo)(nil), // 3: kv.DeleteInfo
}
var file_protostuff_kv_store_proto_depIdxs = []int32{
	0, // 0: kv.KVStore.Get:input_type -> kv.Key
	2, // 1: kv.KVStore.Set:input_type -> kv.SetRequest
	0, // 2: kv.KVStore.Delete:input_type -> kv.Key
	0, // 3: kv.KVStore.Watch:input_type -> kv.Key
	1, // 4: kv.KVStore.Get:output_type -> kv.Value
	1, // 5: kv.KVStore.Set:output_type -> kv.Value
	3, // 6: kv.KVStore.Delete:output_type -> kv.DeleteInfo
	1, // 7: kv.KVStore.Watch:output_type -> kv.Value
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protostuff_kv_store_proto_init() }
func file_protostuff_kv_store_proto_init() {
	if File_protostuff_kv_store_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protostuff_kv_store_proto_rawDesc), len(file_protostuff_kv_store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protostuff_kv_store_proto_goTypes,
		DependencyIndexes: file_protostuff_kv_store_proto_depIdxs,
		MessageInfos:      file_protostuff_kv_store_proto_msgTypes,
	}.Build()
	File_protostuff_kv_store_proto = out.File
	file_protostuff_kv_store_proto_goTypes = nil
	file_protostuff_kv_store_proto_depIdxs = nil
}
