syntax = "proto3";
package kv;
option go_package = "gocurrencylearning/kvpb";


service KVStore {
    rpc Get (Key) returns (Value) {}
    rpc Set (SetRequest) returns (Value) {}
    rpc Delete (Key) returns (DeleteInfo) {}
    rpc Watch (Key) returns (stream Value) {}
}



message Key {
    int32 key_val = 1;
    bool from_client = 2;
}

message Value {
    string val = 1;
}


message SetRequest {
    int32 key_val = 1;
    string val = 2;
    bool from_client = 3;
}

message DeleteInfo {
    bool existed = 1;
    string val = 2;
}

message LogEntry {
    int32 term = 1;
    int32 index = 2; 
    oneof command_type {
        SetRequest set_op = 3;
        Key delete_op = 4;
    }
}