syntax = "proto3";
package kv;
option go_package = "gocurrencylearning/kvpb";


service KVStore {
    rpc Get (Key) returns (Value) {}
    rpc Set (SetRequest) returns (Value) {}
    rpc Delete (Key) returns (DeleteInfo) {}
    rpc Watch (Key) returns (stream Value) {}
    rpc NodeRequestsVote (RequestVote) returns (RequestVoteResponse) {}
    rpc NodeAppendEntries (AppendEntries) returns (AppendEntriesResponse) {}
}



message Key {
    int32 key_val = 1;
    bool from_client = 2;
}

message Value {
    string val = 1;
}


message SetRequest {
    int32 key_val = 1;
    string val = 2;
    bool from_client = 3;
}

message DeleteInfo {
    bool existed = 1;
    string val = 2;
}

message LogEntry {
    int32 term = 1;
    int32 index = 2; 
    oneof command_type {
        SetRequest set_op = 3;
        Key delete_op = 4;
    }
}

message RequestVote {
    int32 term = 1;
    int32 last_log_index = 2;
    int32 last_log_term = 3;
    int32 node_id = 4;
}

message RequestVoteResponse {
    int32 voter_term = 1;
    bool voted_for_candidate = 2;
}

message AppendEntries {
    int32 leader_term = 1;
    repeated LogEntry entries = 2;
    int32 prev_term = 3;
    int32 prev_index = 4;
    int32 leader_id = 5;
    int32 leader_commit = 6;
}

message AppendEntriesResponse {
    int32 follower_term = 1;
    bool appended_entries = 2;
}